Repository LDMX-Software/Framework, pull requests merged in 2020-08, with the labels that each got.

#8 Iss2 - Make use of Modern CMake
  CMakeLists.txt
  test/ConfigurePythonTest.cxx
  test/FunctionalCoreTest.cxx
  test/ldmx_test.cxx
Labels: cleanup

#16 Add additional ROOT targets to dependencies.
  CMakeLists.txt
Labels: cleanup

#15 Remove need for include.py for EventProcessors
  CMakeLists.txt
  python/ldmxcfg.py
  test/ConfigurePythonTest.cxx
Labels: bug, cleanup

#18 Iss889 - Allows Geant4 to run in interactive mode.
  include/Framework/Parameters.h
  src/Process.cxx
Labels: enhancement

#19 don't build stack trace for abort event exception
  include/Framework/EventProcessor.h
  include/Framework/Exception.h
Labels: bug
